name: Feature Request / Improvement
description: Suggest an enhancement or new feature for SwiftLake
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        ## SwiftLake Feature Request
        Thank you for suggesting an improvement or new feature! Please fill out this form to help us understand your request.

  - type: textarea
    id: feature-description
    attributes:
      label: Feature Request / Improvement
      description: Please describe the feature and elaborate on the use case and motivation behind it
      placeholder: |
        What would you like to see added or improved?
        What problem would this solve?
        How would this benefit SwiftLake users?
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      multiple: false
      options:
        - Critical (Blocking my use of SwiftLake)
        - High (Would significantly improve my experience)
        - Medium (Would be a good addition)
        - Low (Nice to have)
    validations:
      required: false

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative approaches or workarounds?
      placeholder: |
        What alternatives have you tried?
        Are there other ways to achieve similar functionality?
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any other information that would help us understand your request (diagrams, examples, etc.)
    validations:
      required: false

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: We encourage contributions to SwiftLake. Would you or your organization be willing to contribute to this enhancement?
      options:
        - label: I can contribute this enhancement independently
        - label: I would be willing to contribute this enhancement with guidance
        - label: I cannot contribute to this enhancement at this time
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to suggest an improvement to SwiftLake!