name: Java CI
on:
  push:
    branches:
      - main
      - v0.*
  pull_request:
    paths-ignore:
      - '.github/ISSUE_TEMPLATE/**'
      - .gitignore
      - README.md
      - CONTRIBUTING.md
      - LICENSE
      - NOTICE
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distribution:
          - temurin
        java:
          - 17
          - 21
      fail-fast: false
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up JDK ${{ matrix.java }} ${{ matrix.distribution }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: ${{ matrix.distribution }}
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582
        with:
          cache-read-only: ${{ github.ref != 'refs/heads/main' && github.ref !=
            'refs/heads/v0.*' }}
      - name: Run Gradle Check
        run: ./gradlew check -x javadoc
      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results-${{ matrix.java }}
          path: |
            **/build/reports/tests/
            **/build/test-results/
          retention-days: 7
